// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("TokensRegexProvider")>]
[<assembly: AssemblyProductAttribute("TokensRegexProvider")>]
[<assembly: AssemblyDescriptionAttribute("F# Type Provider for Stanford NLP TokensRegex - http://nlp.stanford.edu/software/tokensregex.html")>]
[<assembly: AssemblyVersionAttribute("0.0.3")>]
[<assembly: AssemblyFileVersionAttribute("0.0.3")>]
[<assembly: InternalsVisibleToAttribute("TokensRegexProvider.ProviderTypes.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TokensRegexProvider"
    let [<Literal>] AssemblyProduct = "TokensRegexProvider"
    let [<Literal>] AssemblyDescription = "F# Type Provider for Stanford NLP TokensRegex - http://nlp.stanford.edu/software/tokensregex.html"
    let [<Literal>] AssemblyVersion = "0.0.3"
    let [<Literal>] AssemblyFileVersion = "0.0.3"
    let [<Literal>] InternalsVisibleTo = "TokensRegexProvider.ProviderTypes.Tests"
